name: oisi_projekt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - requests
  - jupyterlab
  - scikit-learn
  - pip:
      - streamlit
      - openai
      - sentence-transformers
      - regex
      - tiktoken